name: 'Remote SSH Commands'
description: 'Run remote ssh commands'
author: 'sahrulprjkt@gmail.com'
inputs:
  command:
    description: "Command to execute on the remote server."
    required: true
  host:
    description: "Hostname or IP address of the server."
    required: true
    default: "localhost"
  user:
    description: "Username for authentication."
    required: true
    default: "root"
  port:
    description: "Port number of the server."
    required: true
    default: "8022"
  key:
    description: "String that contains a private key for either key-based or hostbased user authentication (OpenSSH format)"
    required: false
  keyfile:
    description: "File location to an identity file"
    required: true
  pass:
    description: "Password for authentication."
    required: true
  args:
    description: "SSH parameters for example: -tt."
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  color: "green"
  icon: "lock"
