name: test
on:
  workflow_dispatch:
  push:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: Sahrul-Maulana/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          pass: ${{ secrets.PASSWORD }}
          key: ${{ secrets.PRIVATE_KEY}}
          args: "-tt"
          command: |
             env
             cd $HOME
             curl -s -X POST "https://api.telegram.org/bot${secrets.TG_TOKEN}/sendMessage" -d chat_id="${secrets.TG_ID}" -d "disable_web_page_preview=true" -d "parse_mode=html" -d text="Hallo Gaes.%0A %0ALagi update tool Asem.."
             
